# Version 0.0.1
FROM ubuntu:latest
MAINTAINER xhz "xhz@qq.com"
# ADD ../1.txt /data/1.txt
# ADD 2.txt /data/1.txt
# ADD ../linux.md /data/
# LABEL version="1.0"
# 指定多个元数据 使用空格分割
# LABEL name="xhz" tag="v1"

ARG build
ARG webapp_user=user

CMD ["/bin/bash"]